//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Homepage
{
    public int homePageID { get; set; }
    public string about { get; set; }
    public string streetNumberandName { get; set; }
    public string phoneNumber { get; set; }
    public string cityName { get; set; }
    public string stateName { get; set; }
    public string zipcode { get; set; }
    public string mfopenHour { get; set; }
    public string mfcloseHour { get; set; }
    public string saturdayopenHour { get; set; }
    public string saturdaycloseHour { get; set; }
    public string sundayopenHour { get; set; }
    public string sundaycloseHour { get; set; }
}

public partial class MyImage
{
    public int Id { get; set; }
    public string FileName { get; set; }
    public byte[] Image { get; set; }
    public string Title { get; set; }
    public string ImageDescription { get; set; }
}
